apiVersion: v1
kind: Secret
metadata:
    name: decluttarr-secret
    namespace: media
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:i007a3cEGuQqTHbN8TcrjaWF5209p7hy5MdkZL5BW+8=,iv:pbp1AOncCGNPxYhlXnZYJQpiUMCu7yM0CI5Etps3N5g=,tag:dp+GHUnU8yBPUOS+fbY6xg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:mJjUUj1EEUJs2c/bGFPlFg8g/P8ZcygpfVo6k/vr/JA=,iv:RO9KyEOVmJLOpKABD9JKZpgBxdBcNNT4SvOlZwcjiKA=,tag:PiZ1B7gglhF1zRmmG4uCIg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRnFIbkt4R1krdnlWYUxt
            MXNxYjliL01XVUZSWFdTUG1tNUNpeGJ6M2kwCkwvM2tTMVJGYjNlSnkwamIrRU51
            SlpOcDVVcVdBUTRvSmZqalJ3YU9tc0kKLS0tIEh2UU81Yzg2b2w0bEZuNUlZY0R3
            OGNkRk1xcndsc0JoYWZ6OHNPaGpDQUkKAZ55CYz2TtW9cBOrf29Pxov1EhvTmeEU
            jXZOWdFt+PqcG9Fb5JSV8r1rOkqaLcjkY02RFFLb5edAGuH1xU8VyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T07:23:54Z"
    mac: ENC[AES256_GCM,data:/b5JLvF/r/S+pnYTpGCxHCofP6Gyj5Zb9OQfs66JoXzNqVQkDRnFJ3rhIn9bGHamqai989JNo+7VWgFGzbH+LbN3DGywjKD31mAmm5RqEE5e+Lw2GQQlygRbhkhpyw7jVB4DYFBVgOnssKk7EHLdIKP9NH8qAemzSub5pUBTzkk=,iv:OY8voEXD4MyGehm7OnN/niUcedfty8AnDzBiJzBzcCQ=,tag:i+CFL8huVSKIUXsyJe7fig==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
