apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: truenas
    namespace: truenas
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: external-service
            version: 15.7.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              middlewares:
                - name: auth
                  namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: truenas.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      service:
        main:
          enabled: true
          externalIP: 192.168.1.73
          ports:
            main:
              enabled: true
              port: 444
              protocol: https
