apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: recyclarr
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: recyclarr
            version: 13.4.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      persistence:
        config:
          enabled: true
          type: nfs
          path: /mnt/tank/apps/recyclarr
          server: ${NFS_HOST}
      workload:
        main:
          podSpec:
            initContainers:
              initconfig:
                enabled: false
