apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:mAKdI4OeLmVXm2+ayPIGnCk2Me/liaX2uiqvY124cLnolH4rLh4UgXJ0Xwl6wWNtWq97x5nbhv2zExGgUkR2SAc=,iv:qYusskZQyN/AaAXc4e7BzyklEICYor7RQ6RsVU0egIA=,tag:wCBNDP8rDmF73UiILe9XOw==,type:comment]
    #ENC[AES256_GCM,data:JKgiru4hD6srYGgpgk9MSwx9WysOVGf83Nm6hzmtfRe37hRmDTlf+LUDu1c=,iv:YcsrNiObEx4lA6SUUCxPKppfyWHBgMrrL1/InyWmL10=,tag:9gACHpXazrg6uBaWS/e/Pg==,type:comment]
    VIP: ENC[AES256_GCM,data:oeaWwqBnemvGZ8FQNw==,iv:7M7sD/XC0LYby90wWQSO4ARXxg5kzgEr/k+5PqTwV2U=,tag:oFnqbvsR76tdJpPIRQVKvQ==,type:str]
    #ENC[AES256_GCM,data:SQFtqrfSrY2edXlx/oG+mbRAnND7K4Taz2mT,iv:7hchVB8Sx21VJby/fLK+stKHsgdv7/o4U6kikfpPIgM=,tag:ip6mQxuAxHcTCCRU06i1pg==,type:comment]
    #ENC[AES256_GCM,data:5sCy5TYTt36L4oeWWqIwZXBdb2eJIYNspzPgtWoBIqBf8f95IhSGd96Dz4HR2ZGLdaVxzdoHzUDgxC9AROTfq4sQFVnEalHqQoqoZv25HnM9lewsRixD2tA=,iv:fXpySD0JmIV++Wc+N+Cv0r+f4N164Hxa/SzDJ5rNtPQ=,tag:w4bdRD1iMf9pNbmB0u9lMw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:fetuyo7EU/uxsiIjoA==,iv:QCWTfvl7Fkv4B2hxq1bHrD7FNX4/lUh/D6gpVEGwqPw=,tag:7DBWgHEOdI+l6afNlr0BFw==,type:str]
    #ENC[AES256_GCM,data:kwyIpWJN3RLo9mdcg7U0aluFSfQ+tRNLgzlgR5eVVy1GLg==,iv:efODOQ/dakwlnK5s0eXgQg53C+jMeF/xjiYguPhDmg0=,tag:RAS9pbwi4BasKXHDwy0/KA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:w+/Pn80YNtDcgQA=,iv:nFDyha9TUQi7yThTEGbMqXsH0fTL63xmtN95ecDCyI0=,tag:nR9Kh19eXd/f6HYq5eIEvQ==,type:str]
    #ENC[AES256_GCM,data:gkQfXN7hbEbi5WfOiyoaF4FIcnP62LyvGLGd3SlacCY/aYDBU8rNUKxpgCKbffM=,iv:vG6dubcSiDXgmgZWBugwisbk4lnhywKDEXlF/Fp06Tc=,tag:8Yie9iElcHcQ9DBJeNcV8Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:bIEghzOaWvw8BE5BIrcg+uyfrArr4QV7twHr,iv:o7pQHI+JJsc5nJgyOmoRXb9J/UuXS6XNkNth6VohaPs=,tag:0WL00kweSuUTFTwMePXxng==,type:str]
    #ENC[AES256_GCM,data:YL182A65fSexhNzxHzkLhBe/QyHKuzo3MAn0ddnN0ZLc8Ej3ZIB6fW8dyL/h4tQft+HGEoakkBvhviiieBPpTr88eAhzOxHvZb4CwyRp2VDqFg==,iv:PD7WGzYBWXqByq7dM63LTvJAG4bN1FXqlUU9GTVRkkg=,tag:gt47nYAXZfqo52Em/nyHqw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:W25Y05zHfpoqSjbmIg==,iv:YfNsh64U5wuhR8qFUqJ6v0hWSpISG5h318hfOf0Oyjs=,tag:S79WSAbWJpUtuKLN4cIr7A==,type:str]
    #ENC[AES256_GCM,data:k6YXXIDIL9w4acb96tv/SM5FxLnQYMgnuGrpd1+M1mSm,iv:WP55CYzIti3kkipdoYyr3CYUMYo/ZxuXeN7H4AT2Dw4=,tag:zHjLQhFWcaklZ4DaEfBVKA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:JSpmGfqo0iAB+mdV/w==,iv:F+cCn1FdFyIzdKrUxJq05NRyZNfEfl610U1hZjn0X4o=,tag:r6kM+Glvrt3Z13iNrxNORw==,type:str]
    #ENC[AES256_GCM,data:7RuevSRBymsn2fBYoNuMVtYj6YZO2X6tY2mAHGqzqIDNWHZqiOs/FO7UHurnuF32Rsf28z7pdXQh7H0W5qCnphwnAmuXrdxBwsLNEzr8fCg=,iv:FAtf/dM5OMGg63WPg1ehy7dxn3nKnuLWpPTc3gVNIsk=,tag:IGqlhg28IFIhIQrN2YP5lA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:D6TDG/sBY8cg7UmrLg==,iv:B8VXWirWfBTlNtq+Jyl94eYEHGsnDC0SxsUqHEH/SBI=,tag:vGMXxAKql/PQmZ/avfDj6g==,type:str]
    #ENC[AES256_GCM,data:UTZaXMZz1JWhe0DnZv+hMO+zSvc5WGhhR01S0cBdWdlw9pIHCeeOyyux1SGPLLi0x9Jqf/Ls6goQm0WNQD+IHqsWotPKC0+ZrgS0LYjAWxunO1DbpJBY,iv:54MhrhbCiefC5tclIGE6bSLC9Qbt8BlEfv9IvZ/mdFI=,tag:A3mjdVijbbSFedCVZBGOfA==,type:comment]
    #ENC[AES256_GCM,data:9T1FU5yiQWcm/yX+4LvaPIksHyNdBsqSvNCubY7/zdIk4HySAEKeqXHZENRwU4yxzzoa1SLivVviey3/lRElT7lzCkc+ap1TJJfWZpMdzkKsFmDXF2spAaIZI3SLXPWmtVh0MkqH0gigXAdgCWoX8Yztf/076nrdP8wgFg==,iv:hIs6zYKnW6YpngIyRK+Nhd1SY9P2BUxA5Kdv2iaO7II=,tag:CrWlSGP1EJEJD/OWuSfHsQ==,type:comment]
    #ENC[AES256_GCM,data:h8PV+xGRRMVzfBfif/U2itjhatzVSyaFevppxLsC68fM77HqaXtFA/+WKgi70OnagDLXUjuxpkTNpBmUjugEqDO6W4aYWR2r9XTyopFVhOk=,iv:zThOljUSUPfExOGuyEedZyK+XU8l4+XE2I9oKElQoEI=,tag:4TmzTOCjSYMv3g9wfZTa9Q==,type:comment]
    #ENC[AES256_GCM,data:Yd+rYtRbsLiL0FYxIWahbVPyR/Y5WXeJUrNsI8Rogk8w2uEKnRGcTZCam14XWONltBtfPEBe,iv:xCpy17X6GU+VoMOyuniQoU1e209reeChi86a6POwOBg=,tag:/ZECTWy/CmuFnY+Zj8qh2A==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:eo3NGzFSuaAFyqs=,iv:3MN20PVxbsBfEg9W5NILsW5Vk056w65XCrpqcLKEBgo=,tag:emuVdEM4mx2StDOvdlXEAA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:dNxSKsnqKlK53DX58aw=,iv:1mFIN033nUVOwkkYKB0BG1Rst+y/Sq/ywxaM9exdUko=,tag:FdKWptGTeLqE/sMW1WEAOA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:xq1QvXvzAoU4x8NBrDpX+zXN1pRrKcynFQ==,iv:6yfXHa8SqqN0DkL21/fGA5F0rJkFNWjf9tgq8Rzd+/M=,tag:+rs7jK1v+Sy4Pf4r8W2+Qw==,type:str]
    #ENC[AES256_GCM,data:33TOpAwR+trc1QV+XnL0U8Qe5RkYHVIJDC2vIjeNH87Z4At0c9c65RDgLqY/alh8vSjDBygJr+0=,iv:CDE3ylo+zI0Kc3F7ucpKbgrNlYUZXSG9nAyRTHdL3FQ=,tag:elgOiRVf1cSxoAFsFSVNSA==,type:comment]
    #ENC[AES256_GCM,data:uvXuks4BSZokizN+mL8fDZ+c9Z5LmVL10A==,iv:GNce61Sz/gEElHfaa+SKTA6qbkFDubSZXBn2Y613xT8=,tag:it/nOKoWW11TAAxZCIfftQ==,type:comment]
    #ENC[AES256_GCM,data:IiRrtRZFkNG9eCXjXVHyqWpnobPBfopdAWZx8rssOy7d+rXpYkKsLHFHNSSeVAI0nCmxTJ1Fdh59tPFU//Gddvcj+qi4Kwvisx6I6lA=,iv:JQFfB4udhHCvKCrSbXmsZ61GieOfVK5XAH6YB4QUVcc=,tag:RCtmEuM8TYEHv7kdUFR1ng==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:iryEYtC7pJPdRqKal2XEB2igCJPBacEWw9bZBQVCL7oz+uWANsccaQ==,iv:Dh8hgMe+x7nA1TamVTGDhbOq+6OLTQg8nTge9Q7JP+E=,tag:6UnFKhT7WhDjcrp/5Hw0zQ==,type:str]
    #ENC[AES256_GCM,data:irAt5j6kcWcTfMCO69ewH5s1M/6BL09ZegV62sIYJEu+iu7TGp7QLGDknPmGEh/mbxMB835T0HlNzKMWSnGUqJP8sujiggw=,iv:zScYd9a21OW+EfjIdqE5z68U1iSud4saFfvIPnKiHxc=,tag:SOxB7rrJerTaJsYKlQrD9w==,type:comment]
    #ENC[AES256_GCM,data:JpiJNy2n+ZKO4OAy/qBOKP5PQIDKGpdgRDJrPk8Y/9dpG78gKX+QszMjPai+A4GtvGFvpJ+o,iv:Nrz5/pHiOl1WLDlAc9bCBVRvUcUPfCHbRZy7vvdUitU=,tag:l/tJ9ExJGJ+m34QDHcxovA==,type:comment]
    #ENC[AES256_GCM,data:d/7vs78YLKYhfjuPBhVSkYLu0ULelc9E7TNzhjgG9aXJJrM=,iv:hQmaEo4ZAldnbKIRbmDthrJZwPbK6m1yBHIkabv9n9E=,tag:KCSy4kEkcKvZysyMeqYy0w==,type:comment]
    #ENC[AES256_GCM,data:MH1KC+CCBkIWgC+OWkvK2ytMR0hI/fTOc2l+sgXYta3I+HiWl7It,iv:nNziSd1Qg9QH8xZOoBOqPOxrZBXtJz5MpUldC4K1FZg=,tag:zNdx17qaaNerXM42IS4D+w==,type:comment]
    #ENC[AES256_GCM,data:ypV3W0oU8gtjeKTCcKk=,iv:m3aniCVwxe0CbVuXM98iBxG42jrn1xgLDQ3jLPP/BmU=,tag:bZjK/v3wSYGER7pjXhbMpQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:Pw0VE52i56y393ClWA==,iv:p/PMUdFLb9ByzCLwbXq2nAURjSrfFkFEmz/0QgXKsFQ=,tag:czYmkfDCJ5tRLWrlwmO4Kg==,type:str]
    SVCNET: ENC[AES256_GCM,data:0YLU6SzWGvFj8wOPag==,iv:ZWOtGkQrm//YB8zadYMl91uXAjTez4ITPubPIDOBgPE=,tag:IXbz86hu0m3DsrEK+iKavA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:o6Ztlw==,iv:do7w1W2HrGDa6Nvo92xI3snGEsQoVR/cIMA3TCSR/DE=,tag:JbjXNWFvvng12lB8yY0gcQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ2VXajZTQkF4NmdKcDZT
            WEozUXVBVGpZWnBIUlljV1RQNThxd09TQVFnCkdxdHRETUdtYmlUSHVBQ2hDZ2E4
            NE5QeHJKbHR0QnhLKzNqd3VIektZYXcKLS0tIFFvNFZldTlmdnIwMU94em1KZnUy
            bHpoblNsL2l1Ym8rc05aYUcvUDBmSTQKtmPULrNmVV7ehaP7KcIXYWJRcYRJh0zk
            vhMnCGO8aQ3Rotf42htHjT/L72KU+aRRfen/VwHVFXHY6VkH5gyMhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T15:56:57Z"
    mac: ENC[AES256_GCM,data:ixh9fD8YxRYa/dahw9IRAoniIIN7+yk+I5ouE98WEW0KUBywP0FJJ+nexQZPUM3OqArvnXo+ASaawkw5EueNka78uccErbpQrjnYA/neXmcNBYb7vwCvJ0qkrsHnmxjjML7oH+nbrILmzoB5QHUFhvxFjByzxsyCv2YmIkPO3XQ=,iv:eZ7bYOEXc4uaJ53kBjuzd7feaTyckakiCQN3Rlg5OEA=,tag:hw11SIQWcpixgAT8/L/vjA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
