apiVersion: v1
kind: Secret
metadata:
    name: cluster-config
    namespace: flux-system
type: Opaque
stringData:
    VIP: ENC[AES256_GCM,data:/grlfNlf5YRDq5l2Tg==,iv:7nxPMaWcdDR++f0bGev/Y1h1xaCykbPayIQQ9cJAgtg=,tag:nKJ9E5lNOuqkvkhz8FAVLw==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:r+mN3xhsvbvuhmLiuw==,iv:VFigYtv4g+RRxy3SnRvKmg3G4yV/icuXIG9f7ZL2ZMc=,tag:I91Bj5kwDoru6v9oLtLJ6Q==,type:str]
    GATEWAY: ENC[AES256_GCM,data:ZafCVOgkI8UovSY=,iv:1xv5Hrzx3iyJQBa5DWV4D5X14YZCPoM93FdIxYNiuy4=,tag:RaGh07PTY3sOXe4Zv7KTNQ==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:5tAH1hots7yke/YH58LhfCIH3SzKP+f+m9Ul,iv:YK/tEpcoY63BbiG9PwrpPHA1Fj8L5IRYpAshncNykLA=,tag:b4v6malwtTZ5KwLu76TQzA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:1LjvXEhLm+6eU5mC6Q==,iv:r10NmpLJ8u3I87hEVQYSHvVCf4Ke57HzRfLzToOfCHE=,tag:eMhCSgIV+DtIzvdhJdyEUw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:qnApDbMk4Lglspx61g==,iv:5uwtIIm6aGFA58wrIoeq/8B910Fyt9f5v35rk0PmFaA=,tag:F3zBjOsWGTxlIaJr/iQypw==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:15gRo76YU2awzvNrJA==,iv:leyc+usmh94wqzuTWMdLe+TRwPZOEeh8OX0U8AFgi9o=,tag:DMViXEna/5au3XchLQpsRw==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:8LrnO88hQ6jCFA0=,iv:PwIZPdWpe78egBrc7AKLd3ucum5WdFJ7LhZjVgotNCA=,tag:S6rvsc1gij8FH4ABbgZkfw==,type:str]
    ZONE_0: ENC[AES256_GCM,data:mLZo7ggvGM8Ryl01lJLpkywHJSxnIVNZg3j5llaUfaY=,iv:sjUZybmBM3WJkBmE6tp2tkm03JV5SoGJ0uLpWbaKSXE=,tag:gBG4vc68M1lUFCTLyrSImg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:lNbd1A2ivIDfozhPxaBHnjpQxCB30g==,iv:WHnmvvfJI3bGgyZWBuWGeL24f/u8PmwJ6DPvgpJGnFA=,tag:wCobcKQokcPXKMze1ncIhA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:XEqw1cp3Ib5G6LvICIAXg19gbSkpk2dvEE3FhNgKuO84ZUbRVOvVZQ==,iv:DdS7jiXiteWiK1wH51vrQElVy6dj8rwuQ2mS1Xktf2Y=,tag:rHKfNSdjENaBrujpvCF7jQ==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:F+L/co95z0y56qpxZptNbW3x6vPK4sRaFvJQVRoFi6CFBPwHxyK60w==,iv:af/vdQnYyt8SIE9EUTH8axMWWr0tsDWHxw7Bj8z2dTM=,tag:t8aZPigp2xcF3iqGT5TgIg==,type:str]
    PODNET: ENC[AES256_GCM,data:/LpJk3anczhIJT1Msw==,iv:oJqghlgzetXJyd5E5CkAyxYWUnBGk3Cdbl2TqYwnPuI=,tag:3w4SvCDocGG7TFAYlUdEUw==,type:str]
    SVCNET: ENC[AES256_GCM,data:J0Ti5e6x6s+fT9ZUaw==,iv:egsxjfD1pql0XQ9C1yAF1CCz1RtsPrYBTrLgt+7EZlM=,tag:4EJHFSMYenWzSXsLsYT6wg==,type:str]
    S3_URL_MINIO: ""
    S3_BUCKET: ""
    S3_ACCESS_KEY: ""
    S3_SECRET_KEY: ""
    S3_ENCRYPTION_KEY: ""
    DN: ENC[AES256_GCM,data:fGlFcKxaJA==,iv:VcE/6qpyl+EV37RunRUoog8rm4lWAmaM8rsAeWrZfik=,tag:tMxiGoGfkLNUffblpXkxfg==,type:str]
    DC: ENC[AES256_GCM,data:0GTL,iv:CDFQ2R0YJPda79qZkp4UWpHNI89p+Opey3EDjD7j4jw=,tag:B2KuogpYoEZQrUrhyYt/pQ==,type:str]
    LLDAP_PASSWORD: ENC[AES256_GCM,data:wGGhTOt0L3TBVLXV2tJJ7R49jeYqobbt7p4C0I4R,iv:0/mZ0cLYWdybyDFRvsgst2EX8wpnCZrCCqhvVE1h7IU=,tag:sVpVYRqUb7993/SlQSexZg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:frOD2kjkrFxNzKOcLenQqJHzJA==,iv:VU8XKS5nYYy3C+jSxInjx172xnb9GUuy5VZ1WzOYbIs=,tag:5e25o0pF+KuBYJ0bJc868w==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:CEE7uG6f+mnnOVpiUTU=,iv:yT2vD0CsVxlBsBQ6MNDKpwsyAqCHX0EmQ/PIV6H8zUE=,tag:gG/ltAVLp9Y7XnpXydNdLQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:1fOVxdQg5f/hSq02YKr0Uvm/SQ==,iv:bHVH6RgZZpsGqP4BdIabzYqQcMo8bS2FCR7k3UNYwo0=,tag:eUFdnZJ1OpcMAZsmA9XryQ==,type:str]
    NFS_HOST: ENC[AES256_GCM,data:H+GDBc0+z8O26p57,iv:di/cG7lAxDd4R0fxWkUc+S5u0X6dX2chXL3I8K+tk14=,tag:W0qLN8QmVCS9cLj2P/Mlvw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:a5La2Dx3OoThi9DcBXVnqH7hr+8B1Qj2SD402JWnm/cpRi53+A==,iv:mOGWnMmuUTgn353GTBmuSsBYVO9FrPRoftPpaOJ9u9A=,tag:Vp6+imibj0XDcfXcXEYh8w==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:3mcFOBsPmNhq,iv:AGl5UmyO8RXD9Pozc7q9vmUK1nk/1XEZEW12irT+N5k=,tag:hNsbdiIjMehedqhZqwvWig==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:P24x5hgC3cB3wMN1e4LWZQ==,iv:VxU2l+xQk7KLVSyO4n4tVQkNI/8gavm8YbFS8z29zAQ=,tag:Qf49Ffq8Ku3US4DDhaegUQ==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:OTW1PAc/yNChOOP53yDR0UaezUwSSCl2tQTZO7fLQJQ=,iv:BtQQi3E2UikIrkMqNk4v2ikbzgVp8mIJJaThRJ3Uslk=,tag:CTp6OUbWseLZrR0MaqxVQA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:f4cH+z3OS1QyPWs+1hSG+Brc,iv:XhXLRaXB7Io1sln+YQSqmus/vrMeD6fwFCYnzmKwP5I=,tag:qv7qBH0QchQBWF1pYUMwpA==,type:str]
    AUTHELIA_SESSION_KEY: ENC[AES256_GCM,data:l6sJ8a/nka95XRGx6K6DyHczSfhcI26n1SDIMEbReAU8y1l9df2U90QXn/2pCMSpRfOxIBWI8RCkNGJoSDxDU4M=,iv:mzwysHk78JTT7ZiGuLOwtMDnoUQQ/GNf65x30Ye9G5o=,tag:3UP5cgjzHXfGX9M11iLgpA==,type:str]
    AUTHELIA_JWT_KEY: ENC[AES256_GCM,data:q3XJZaC+mDgfwAAq4Cg0hRrlRl3iauTUInh4LS/9DrInm4KIp08EJUkvuK/Eenm6g7iLKF4x1JL8KbTN0hKvYOc=,iv:j13GPX9p99Zwqy/rwmezhS3l6UBpAjW69yuFGSLWxEE=,tag:lKp7B2LTnhkc7K2h4UGRCg==,type:str]
    AUTHELIA_ENCRYPTION_KEY: ENC[AES256_GCM,data:HA7by5DA0G+M96cupNnYpFKv2CIp4vWIdrfztYOtJfAw8sHIIL15eWyLtUluRNBSr7unKaf77SBIb5SjM8ANYg==,iv:/YclRAHjG7K/eO0EN6vx8m2bfBueYKkNnKZo7UNEOVs=,tag:SrloGr7L1qsK+MtrOX31sg==,type:str]
    WHOSAID_DISCORD_TOKEN: ENC[AES256_GCM,data:oHHatumNiYsvvkQhn9rcYEFhlt8fWJwM4XNS/JtE7vRYxj6DyGKfZCOEFKeqTYRlERi2FAsv1n0g9MiYUXAKTVE5mYKHQg==,iv:ZkPdD4oGbA/LkV1oRCcNvhP6GgjUtzkPTENNGbeK5tw=,tag:AnxQnYAGI63qJF7Kvv5Xag==,type:str]
    NEXTCLOUD_USER: ENC[AES256_GCM,data:mNsmy34=,iv:4G5DszVqDwhWLweMrJz+5uHXuIvL1DbhCcd9EjvzEps=,tag:C4OPVkJN5+Cuo0KIXJM/hQ==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:S7RWRQnWai87v3vuTE5o8VQM3BM=,iv:cJWbFbTp1ip688JMabsMxW8smSMZazpkWIy4Rg776EQ=,tag:dqY6hsEveX56GSqd8abpsg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:W49p67nSxgRLWKhSPq8U+d4+LC1jYBteQrZ9Uhez6c6vnUjaB4Qk9/IYYzQ=,iv:kHQU299jiLD6pH8eqSynfwyvHKLq0EnZt5Ryb9xI4Ro=,tag:+QDwEqsUPMm3E0xg5Kp5RA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:qcfR9No=,iv:/MmI70NNU/1Vx8L9DbbLaUJl2replg7PngIBmXgZcTE=,tag:vM5YE9DKpoQTPUY5UWtTtQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:G230tKBWexS3IIs=,iv:ViOluZb6XMXKSFvVUbu/h5F5hl+fCSZEw1Navxc7Bbs=,tag:89wI46u+wKiWnSqisLgDvg==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:eBpADQ==,iv:fyjkDQpSyxxJ5Kv7A3ullZMtevhX88z/OY5tYknfju0=,tag:y1cwUvnmWUGg4JG8xxFfsg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:L59tckpLnR9wGp5+GyJo8w4/JSSp7bPuMcI8epyaYKfQ3tZdJKfzwxK8NhE=,iv:lX3ak8sYhMkTwnh/abiUohUN/Et+1OgQ1cL0VMUL8PI=,tag:bBPB67kkwTLouqjQypDzEQ==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:fafKYmvgeD/yhETU6A==,iv:yBgB+vzvzdQjZHzJV2c//AFRcTtu78dG6Sta2glPSKA=,tag:gs6k5zogxNq0EZa8x2TZvA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:AXaqJg==,iv:L9TCI+74M+B/zirDyAr29IIkr0NfAYvBv7EPRwZBUWM=,tag:om+NiPCfEvpOm9/hw4qdrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaHhGTWsvbnBCNXdyL0Js
            aUxHdmNHUHJyUldDWUZsWnJaUzMwTmhoQ0RZCmlGZWR2S2VTd01STzBFUDNRVUVi
            NjNqTnBnMlpMbXVJVFUxYjJrWHg2N0EKLS0tIGk3UlU4UzBKOHlsL1I3elZCSmg2
            ZnhRem5qVUorbnY1YnNGbGtJSnF5ekUKSjs54tfw5WMg9I1yuoeq+qh5YZRYwpIq
            8vi2NOpPZ1ODqZUwqxZgPiN1XEfqyof251qJ+Xg2vn7v2Evyq4jmrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-10-07T21:57:04Z"
    mac: ENC[AES256_GCM,data:bPGAekL3olML5QOu3cTnd7BOyPZsRzTzEVeMtSCpCxfznH6obkyl3b/3+Ud8R+U4UAFc76GWKv5iw9S6B9f8Uz3hVSvCui/BWCbFvOntq/VVdaGhNLmj6FdQP05y0mbp70WN1+1pf6Ro1SJozlzIPY1JeY5VjFQIKc6oSlKAguY=,iv:w2uacJKuR64US/yeQAFR0sfg9MGgH44DA2MuIzsTzMA=,tag:L/E4ckia6b+aBfRuvRhi9g==,type:str]
    version: 3.13.3
