apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:YDN67GrVlEJc80Qh2rFg4J848eR/il1ad0v7cYm2sSI7eUIHGX/Vc9dVxphzFILVBFL5nzQO2EWyT+bfCijg9Mg=,iv:SXQzQ+/U+6E36NB2aV1bVr9RcOGRCL//gfs8Jkm2VIU=,tag:+sbYmtaxKz1rfCfA06qj3g==,type:comment]
    #ENC[AES256_GCM,data:cg9ka+/9VSsyTrtt1+wLuCVlCheBnPNFnndI0D8Dziq3TS3FSyuMvZQV48Q=,iv:TQFdbX2Gra9ePQuvH35UVF4kdENXdIYoD8JFiBKoiQI=,tag:Q+N82W1x9CQWBsbTwZG2aw==,type:comment]
    VIP: ENC[AES256_GCM,data:jP5HKcwN9k+qCXdNvA==,iv:XpRfkwjBUlpkWyOfPZROGQi3heO206CeeQDqFtKWe+k=,tag:RvL4qyNA9eKT5ds0wXyksQ==,type:str]
    #ENC[AES256_GCM,data:y8QTDKbMRAb6WyeoNAnnZU1IHFz3PdHzdMPV,iv:aASaguxeqr0qvvEdCP7B2PEOjOIyL7Pbn92lsMAm7PY=,tag:mbUYe9hFu7H9pM2NDyeaWw==,type:comment]
    #ENC[AES256_GCM,data:h1f/DNiHSxJBYaEgdaxpzRSRdmobEnbLojHQzP3b1LPz11jxJpNd9Qjzd085+YTo8Mjl+sp0R1wv1VXSf/xUkpdXidEXe23MRnjbu7LMtAduinerh7PB3jM=,iv:t+tA9o2UGxdjY3Spde2oJeoHZ+yAWkrXK4BUWURx38Q=,tag:ip2xpfN+w/lHJjCh2whmrQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:/73AMzkDbFpOsxabLw==,iv:2SmNmGSdwF6qKyESkGctJ4n60/YW1if5iMYY/xX/doc=,tag:fDhM8ZUDVP+19GqRBVqJiw==,type:str]
    #ENC[AES256_GCM,data:sSeAH2bKZ44L4htYKe7cIIzf+expxXiKNPti7kkdVtoOwg==,iv:12tv7/uA92AzvBWM3N67t2AE7H9iG4SfM6qzHP+Uj78=,tag:Skh8JgrhdiOXK5M5ZMI9Rg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:DmxyYnFBMZPTBw4=,iv:xm5ffwsl0c9MysyIamcIHbugc8GrUXknb2XRPq2APms=,tag:RfBytMyv95dlZ8p+GY//5Q==,type:str]
    #ENC[AES256_GCM,data:ejWpfWpxXn132wJgLoVax8ZFLOMqgLwPanfslnSO4ELQSk8vGbTX1c5FMt8v5ro=,iv:awyBQGJ785emLDy91lSwfEyvIGOC9HxiMIhLfEtKlWQ=,tag:/+oDabDTSUz2W3OeCSGbhQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:LdUZ8m7pKR4FDkzwLCkxEAc/NxqPlsm+VLER,iv:nsiXuK4wNKAYwG4lZ4dwS/EU+LLUm7KYMHEqOIytcXg=,tag:KPvGTsmpfZ3vWEPkWsA+dw==,type:str]
    #ENC[AES256_GCM,data:tcMq/tAZpeY514QvYZwWI74cBooQgiwAmCOBDeac7qMKkzJXQUzx877YeSUzeS3SAjmKQFhP7yrfJPlMTuoUtPkBtpBfsdN+XEd3YhIa+SFZTA==,iv:zevhzgXzZYIcxR/iuuN2pGblAZAjY1z8h769fP9Df+8=,tag:1mWshGcKlal0XM4If20szw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:OL3xMZxiROyX0GzZjA==,iv:mH8Nqh6zK8euPRtyUBwlXp2dN1BiI5ZfzIQCDz/nsKs=,tag:U8qDvHcAAmROVA3aPQMRng==,type:str]
    #ENC[AES256_GCM,data:3mlP2lanMCuZOYFsKi4TYpWmGclJ3BuqK8cDl3uqCaaw,iv:fXizs82jT+U1XPTdfgq46Fq04AY70BYWA78nUetnA5I=,tag:1hiQjAgZU7WLN8r8KpW1Cw==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:o1ZpvpSStyqSqcXEXw==,iv:YMRQtY3t4wkwWbVNaCuCcqU301/mHY64KsOeOcgJLnM=,tag:XfPzX+QZvgLRt0ZTn5LNFQ==,type:str]
    #ENC[AES256_GCM,data:VptQcTBVWerS3b0RJdqJBZZbreucRovH5ksOx+uoC4phMxCe96qTUabfMkPNC/fdLoePS0m03E8tJKCXWgFaK+JYKgzoCQJ22bYN2N8SKTU=,iv:5l3vPefPYqa8kRRPTdE5G3VBoSxmvKBNUvywdeTn2yE=,tag:f+VcniYEGw+/W4RH1jPnog==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:SwEpM17oDVTn7/rfLw==,iv:CvyHbdK1WmUj49LMkfoonSaS72oD28Sung/7GAcITts=,tag:7GPE3n0KGCdDG7B0d9ZhWg==,type:str]
    #ENC[AES256_GCM,data:sZcEhKfsOvyOorf6zwR1eaku9wUNxucbtVCrkQI7TVHoi2bUuB6qWdCXteG2i+zNgvOHqFwN7ZjyWEd6z6ilez3EklLeXWHUvBzmYFgbIYJRnZXqFFOS,iv:WMIXMOKHA0RQ3IX3TRp4XOWjzpPfzBy7G+/hwAGD6f0=,tag:L2t7QVb19VO73PFIgmwoMQ==,type:comment]
    #ENC[AES256_GCM,data:mgBku6p4xShH6GobEnRqevipVywbXZ9IUaNTfn9tVYXNKiAZYSeLcyYaMr1jSlScng50kcVXFRoBGdlDf4uvvdpU0NqdOmpVfZOSwhKfRe8RAQxgUBRpdlMgZ63NZn15E8+zv2hE9atL3zbtRsXFeXPpMRjnc4y1ydvOMA==,iv:J0cPMTbl+w6lCzltQ68N4tglXtaomBOOVQbKg+DNRNM=,tag:QC+dQil+viPudePigBHy5g==,type:comment]
    #ENC[AES256_GCM,data:+jbYBkFP/YTij6eOPVKp1JIzKrrPoVj1NBabZEVWEBtEQzfz6iA9il0cKYhf2p7A5eiR0YMJRSQJLXyDrXGLrvtGZVT3uX4QAjqAFOnXTOk=,iv:4y1H20W30p8XIIa5S9TWT9m20AVvCNjoEygBsTwm7No=,tag:kQ5eelPKEy2l5y2pHpbtBw==,type:comment]
    #ENC[AES256_GCM,data:+ZhF35UIJgl07EooZfqUBQ1cHip4QKZtuvs6LVDd5ARcltJUEPKDRF7/MykCicHKiQ7b+rzr,iv:GwF41h31h8ZjHbS1DqX5DoGxA52wbqGU0u2v8OPMGZY=,tag:VrgtDvEpwFY4fCxo4yp9BQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:qaPMme7v0bgCXNI=,iv:SpW15xjw1b+zZqk0F6PfHaQZGvHOT1im9eo6dXdOtA8=,tag:XyfhPzc03LH7zoZOj6F4uw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:R/+AZEdiv4JXpslICoSf9GqjYVjllw==,iv:mxfLq44RcPAaVIsSKBkhC/pZodvHblcmie0N5mwqLLg=,tag:KI/JUuEQG0cBdJx/C3txsw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:6mGYlEFrbdJlnp4OcZkeqcx6+Zwlo9ewjEihWWrWGPl6ITfqWgUncw==,iv:YbAVdHkuYU/wdP6AGZqkXe9gfCNyiDV3MUXlazemnNk=,tag:d04dIkjeOUDaGRko598T/w==,type:str]
    #ENC[AES256_GCM,data:CowfUUqzkL4sfLhPC0yaNjp6y5XTDLezfoOMPwR2c/robhPZAAG1KxwPojL5/H8hxPd4s/Kngkc=,iv:pa+FduuKSqURcfHQdyBD+jKvINEKg5Xe6IMy0xLK0gU=,tag:mMo1gShXtHcsOUBbC5Qghw==,type:comment]
    #ENC[AES256_GCM,data:wI7G0iZd1uV4KiHdzbKBlgfhGr1C6782xA==,iv:ITT11lB7UgpL7ntsGb3HCK3gs4pItFTclqMr/Zmi1q4=,tag:eUbBIRYYEROW/pXTyiQWAQ==,type:comment]
    #ENC[AES256_GCM,data:mNWgJVVekWfTZFCOgxGWZER+HAvQArSDSzgaMDi7NEqKbD4UYTyDN0Y4dDdtLy48BMfAuLL6lZr1dkESWCEPRYImrBpDJG36bm1VaEQ=,iv:457OHZNPj+t1kB+JIeNbksxlrofXStgddMlvNiA70+4=,tag:gqEWzB/QgjCaSfT6WfJsvg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:TSA01pWF1NeXNzIssF23rTob8EFuZ1oe6joS64yRyB/FgKIAmvqYbA==,iv:FTP6Bt2RcQJTq0PGUeChSgQHtrGXGRitUuj1APvVPOA=,tag:0XVfP5IrajeHC4GlxYePfg==,type:str]
    #ENC[AES256_GCM,data:CjoFmziEus2wNad3mfNzxZm7Nln6SH1zWAXvjn6fCOegCkh+vhlBr35cVtFLBwzRxOufdUogRq0vPK3UmR3wzz6+7xUMR8k=,iv:OVMGcLErBsLhCNeMk9hobnWm+rJ2OY+0CGi/F4BDn90=,tag:rEjRINyUIPFj5q4QXNmb3g==,type:comment]
    #ENC[AES256_GCM,data:2PJy7qRWN+hZfgIrOYHNgLS/5/8Q6BaDdzqY0bvSE3oGiVg3tjgr3bIf+CmQh1kIgkbDnwZ4,iv:Q8jhn5cE9nOxW5+CcG20t8T69kr52YOphaKB0uQ50SE=,tag:IsysbUs4+y9EQveAua5okg==,type:comment]
    #ENC[AES256_GCM,data:TgOk+9qbTU9sGd6EoG/H92Ny062PbFbH4mUmVmzqH52TNjU=,iv:nHISGTn2Vt0JLitbqhFUEbW3kPsQWbA12SmJiIcpXVg=,tag:om0IFsPse9bQFYdWneD9kA==,type:comment]
    #ENC[AES256_GCM,data:M4e8kXQ20y1xx65+GkdDvSVbZhMqupiKZ9vD3yo1kUvqLYzGsKER,iv:8ItpRtFgKsOF5XZEBCMi5tKvnRWwrLkpyC1LdUemSIE=,tag:7kjKBeX6OPkK6lzYG35buw==,type:comment]
    #ENC[AES256_GCM,data:UW8tampnF5c3w4Ot3mk=,iv:pgaQCAFkUAdvEJU80M28VfGLh1Zmg/Fnue5EGTq1vy0=,tag:pM2ytfr6PWzf4yA61sDgbg==,type:comment]
    PODNET: ENC[AES256_GCM,data:yTui2xRS9qnlSI/7jg==,iv:bU4w+yjV7cG0Ymzbho9GlW6ZYdnekdPvCifbkSOoPGA=,tag:7sDBKbx0tawsXMwcor0I+A==,type:str]
    SVCNET: ENC[AES256_GCM,data:KQkh5jrM8GKeEfwYzQ==,iv:vwkWiJ9p5KKD29W3oWqjvMZTKjVJrzezFwmPpPlAU8Y=,tag:9lWiiP71oIETX6NejsoV1A==,type:str]
    S3_URL_MINIO: ""
    S3_BUCKET: ""
    S3_ACCESS_KEY: ""
    S3_SECRET_KEY: ""
    S3_ENCRYPTION_KEY: ""
    DN: ENC[AES256_GCM,data:6V4t1VsK4Q==,iv:M4QEbUSzzL31VsXqRqJIeu7JsaS5EUGMX7bLNSQ5fgk=,tag:dlyEBaYQTP9bCmkJZmnXMw==,type:str]
    DC: ENC[AES256_GCM,data:Hyz1,iv:bZLVtWjLvQR0pJC6i+bufV7KRUL+iaZUPjGt8/PBJOo=,tag:+ZGYzkvkkzOmx+nDPd+1rg==,type:str]
    LLDAP_PASSWORD: ENC[AES256_GCM,data:tqjj6+4mhebXGwBL55d4Uy57lsG4t+DOaUtB8vvt,iv:jE1R/Nz1i4JHFWK1N6Ahia4koOjeA9GDzQWPe0t7ucw=,tag:UqmML08nvwF33kyzxf/HJw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:sEYaqf0pXSZTKqlFh+EB3QC5sQ==,iv:+VjR7lRjBpqbcAH4BuFpXbl0obwsf3G3zOwhqnZVjKM=,tag:IYb0dHRS7gKNQQcK2LOZAg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:DxdZkt5KE2LokcFktdM=,iv:QyrmJln8WRDAwWvvq48sC30FLqSdV1qTdgzbtz4hDyg=,tag:omafDnZ/bSsGE+i9j3AITw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:2BJ/+TIuQWtVPO3zgZFl13mUTQ==,iv:yNQ3ugPKapiR3PXxgX63ZCsd3sCPr3CX2Q+psw6qoj8=,tag:5EOMaWkHT9gwvoD/TV9mOg==,type:str]
    NFS_HOST: ENC[AES256_GCM,data:SX23xbrvdz4XtGF6,iv:R6SfouLZySzMMJl510YfAttlx+mvbSlvOAcrQ+hkKOs=,tag:fryIl74vjoC/aXcZrDiopw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:5Ma5UQ==,iv:53Gdj2w1h7TByG9ytWVOsOeXHwn4XnmWTBdZJ/rfS84=,tag:MJrlPEjTib7VWw9/Yw1Iag==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTWJWZnRiM285bVZZenFF
            dk54djRPbjNnWHZjRFpFMG5nZ3IrdUJ3em5VCjcwOFlZMU9vczk5YTFWT05taTRy
            QVRsb1ViSVE4bStpSmtiQTdGSlNLYkkKLS0tIHRJU3VkeUlEb09VL0MwVG8wTGVG
            dXRnaGJkWFU1Wk4ra1JXakdHL1FRVjQKdGS3xti/vE2fBNSx9zcMht2E7whfxcOU
            5e/FVjc+OqlZgHI87WitVqOEuKTu0578U62Bddl424OQ85TOV1R5Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T12:50:16Z"
    mac: ENC[AES256_GCM,data:FCnWjAi+HFrMwz0aw8qj0y5YKv5DfovyRpkIjOnNK7X8VX/MGmu5nEGnai0FBSgPANnatIHrx56s+OgNiZeoQ91u/PRY6/HnV0zGEAJ6+R2iFQy6Ep2F3gnNXy/oxnuNfdYYiK4iUD0T0iJhLG755W0uUcc6zq965vtg7U4FoX0=,iv:hkTc59fZhz9Th6bClUy4Qr39Vk2qkjwLU/TxAx8Oxno=,tag:H06rN3yKZKpgK4WErp8o9w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
