apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:gTIK6aKUdn8wL/xKNomRKdCprBjSjqUKJLYe+tmTIC2CBzyzY31COY8mJQ9MgjOJuMTQnwjDvtlOpJMLB4CsWHw=,iv:PiWR1cEfWyIIgYlr3K9qcC8MrbQ7mtwbskYRf7DHnsU=,tag:MClQU/8/xRFpxnYz1wctLg==,type:comment]
    #ENC[AES256_GCM,data:I8KUuXf6W4Elrfnf6b3CU3ffAzjYD0PrgSD8BT5vBYz06HAZVFEQS55DC9U=,iv:jz7C6m3wXfZTtYishkyuUbHsTDoQQgFcBCxQbuNSoU4=,tag:zqhMDu6dA4WY2+mDAbM8Qg==,type:comment]
    VIP: ENC[AES256_GCM,data:/hZdFfsw57RdrpfgSw==,iv:65RulNVWV0wQgWdue+5kL0XUUu03U3sXM49n/YcH6o8=,tag:umvQEVWucgjeHEGdVNq0FA==,type:str]
    #ENC[AES256_GCM,data:HDw4jP5sLprgxQhW7/hGK69vSVhSWpUGjThd,iv:hNh8DHqOH7bDafdkVStPsEOl1Yiv1KzGQHwm+r9atL4=,tag:21mVuar6xr25/v7UFirK/w==,type:comment]
    #ENC[AES256_GCM,data:D3JypHAM6VJUQl5o4ukIKmshKYJIDAjmGOaRC7Kf5C1wfrAqhuu7xp0YGzzrqKoUp/+YMJgfdvFfbRUiBbD98Y27ZC/uzRcH++AtVFhTNCmfmrjBx7eNn5c=,iv:Spl+cYLB/h1py7q4HIBK4dNrB/VpG5lkMMGAWiDIWO8=,tag:P7eNd0FK7gn7TjjcZhZamg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:don3yDMccl31/PU4/g==,iv:FpGeHrEDqLnJW1DVQvoeKXiOFPc6kRI9SEMadAPmLvQ=,tag:EZGERmNzDgkA5DOS2SzACA==,type:str]
    #ENC[AES256_GCM,data:sI7Co3jJQ/s5vqCQLr2d3WdxMI707xf8MjxduJUh/qRUug==,iv:UAN2UI6f7CRKuG6zfAiwbgHCUD1MUFMaF4JpmiItWZY=,tag:7stpC+bowRE3my6TzQnETw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gvavRYK6WJ76TPo=,iv:DmeqG2NVg+1/Km/xNKPF3HBCPcTQndSg143uRop6TnM=,tag:qoixIIESTi2cwtsibs2cDQ==,type:str]
    #ENC[AES256_GCM,data:GcUHV/t4ITkB5FRKtTy4LOvgHGFVopMASmVOYaJCNzztwwDl1+3XwwaS8sPshQs=,iv:VSXbINuzT8IwxfemyBdICIKmbEinLWLZcvxnMLFMMtc=,tag:jBgIMB9c/JtKAzzPwZFidQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:+W57JA2KcjRS5E1UU2DjANLV18uUggvpuy0M,iv:LmpTQ1UdERMgl2ITcpr4v1/dnTpL1O9wahTvuLPHTKE=,tag:JiNbFXLOpgkvVqGE6P1C+Q==,type:str]
    #ENC[AES256_GCM,data:AoLvqAogr6hOjaViJh4W395O/KJySac28Wj/PMmFronG1MGqlvk1JUpLwcgqXoAbiAq25x9Q4MAn0I9gZfj/eHqPehH8YBXBO371KC0pVwRShg==,iv:nxp5jpbgjoydJ8M0gizXUzew+vwLqxutJRPF9agto8Q=,tag:qcSCRaY3FU/nCkv1djOWdA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:kGXSjNCLBGoEdU0UTw==,iv:sfhK7X1oS+76/77Mgr8TtY5IJE92H44GaXeKSVnM+zA=,tag:UoNgLAGLoGsy58pELojOdA==,type:str]
    #ENC[AES256_GCM,data:3SZbRFnqAfGzx/bywY+wAhIeiy3ulk1TNvXVri63sNNQ,iv:x30bYuxPqVa0UdnAyUv2v+5PxBNvOBFJ7lTURZ/mLsI=,tag:qAW70vsdEhKIsrMwbz2pDA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:CrMPjb9R/xFYMSB5Tw==,iv:U+zOpW9AEml36ZOGL+rzYkdOZWjPu/qwXkFc1IwufQ8=,tag:2cYPqYRNBYBUOcn3U/yOHg==,type:str]
    #ENC[AES256_GCM,data:/ix8t+6Jy7xBAYHNROkK6mEh3bLuCipk/vOCuRVNxAAOR+Uv30L9mW7zorHxIMNlBJiZeNfIBfkMAvl2xQR17X48NezwRIAEszy7n1HF0Sw=,iv:JP6b06AGB8q7WAHCsL5UeHVgETfMr/Z1e1BaCXMVYsU=,tag:f8dWDzHXg/gXocln7WdeMw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:xZzoUc8p+I1adzE7Vg==,iv:ttNZ+MYTbnKYNOI97ShViIU/aICF7TvdwgtccQepG3s=,tag:BFZikQcP661YtW3TipN7aQ==,type:str]
    #ENC[AES256_GCM,data:mGb0W4M/NZNfnEdKW5bgDNtDyWQYt3YF3quBQl8Z2s8Z30cEz5dzNjU7ZnHXccvp0VkEGy+/PEVWX2ReiYSU8Fp2/HdoA3LcFRpbD7qUeZEC6vuHzYfP,iv:1IgyZvk+e4tibY+IKMmVqktyc/GgCkqJL0noy2pF7IE=,tag:BA92XdF8Wt/8eyn6hMhivQ==,type:comment]
    #ENC[AES256_GCM,data:KNkArxRkfTJT6jMnGVAzFmmOVGwCri/AXGk5DRP3nd1gMRcHBFFIgwJas8i4td2Ge5j0t25XeiHeXIVSbFBZiJlt1/XUM3PVFjFDyPRnnB2GrnbfhVwEHDPPepSQgXtkeyF8u6IFA2Ba+oYb2lsU8WCElU/451J9YNF0KQ==,iv:zZvmFwrSyDuelmoIm8czTenT4gOHwzClEhTFgty6Y38=,tag:EB5yHrz9NxfHvgEzFAMBrQ==,type:comment]
    #ENC[AES256_GCM,data:UqOt9ne3pJxzIoo8wb7qz77q68MKUNAPI0B+Mph9Y5vGv3HZmus9C1ApyAT/bl8NIaXsbsDIstV2MuLwHlwCgSMfehCVdTrHwQ4TzhO4Yco=,iv:drTjq0uUrioRIfWeoFKw/Q1UZ9dXDI5sWVkR3f8AhZc=,tag:KbWu6gWtzJCkRNlq9nB8eA==,type:comment]
    #ENC[AES256_GCM,data:mArw3D0MH7QypwrtHUBzkEdGv+zLBppmZV3yTrgQCgZTMCRpBKdep5O5Lw5uNg7qMw+r36+i,iv:lodZYJ3n0BwfJylIc0Uqo0+VEZuNdNunZCCvIwTZ3nI=,tag:bSE4V26Y1eL/sC2DKLHC7g==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:9aly6j0qeAFXX6o=,iv:tgkCe96u3VRhq7qkeHizo2Xj5U+1q4Fyot3wduIWvuQ=,tag:utaP22JqZn+dCA/aN/tE0w==,type:str]
    ZONE_0: ENC[AES256_GCM,data:owv28tEVtRdfEIxKJ+h62Eqy0ak5hwJXOxQpNcPCKQc=,iv:ODlOrOKKXXP3MpNlvGlDuiaNdBincOHH959ydurq9jk=,tag:bbBpoS0Wvp/o/gVJ4eMKNg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:VATmzOuLkGtkGg8purufzDAGRL34gw==,iv:WzakyxjesfJmslLdA3B8QdJ/NnMHXKwdSIkUHAIkX9Y=,tag:UVnOyNmrGHcIs9kHaBuJkg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:8pCwdJXGCURzOY32m9w/CfLbJ0h/+yxdM4Z4GW2KMoZvpNRjNaPFqg==,iv:sEakQf+vasWEPdq8CU3BuP4pVt4gGshc5vvhTB5Ro50=,tag:EItEypkmPY8XYmhwMn+2Zg==,type:str]
    #ENC[AES256_GCM,data:2/TWAWMYEThrHzQowrBpXPXmbgxt79VrTJfBkIiEYvVMNK81/sFFDDDxnr8g3+k+KXHYPNT8clo=,iv:LUXqWr7iSVwzpZg+4vLF8V05bHMluoaMht882dV8f8I=,tag:zZfxKcTFRWt5un6AStRZLw==,type:comment]
    #ENC[AES256_GCM,data:OdL8xbZmkaWMVigUc6YrDLezuRK/4zDhRw==,iv:1aSPPiuOP6SINUnZXBfVT4hpWDuZyhNlAnaDOGzPpVk=,tag:v6XeiKlGGMumhUBuo2WQiA==,type:comment]
    #ENC[AES256_GCM,data:deT/V2jyZYpUbSUUxIgPhZVW6n0hyc/SsiolYw6n1U+wdWzu6zPiW/bzBqBB2Rtva703Q+cq3Tj5N15Oj6VGfClTtg0cgkrtG6r3lCE=,iv:R5nR42O9Ki8d0APCq3kxs4JNF+RdyG1ucAklkfnkOjc=,tag:jSnNBycFWwWnJoPKG5KXzg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:nSuh8hYFSBmJwZkimFO5KRGRtloZ1GkUHyTIoAH9d1xJGzn4c1es4Q==,iv:l+8qGCaagIj1gqj87I5Z5i8FWRwmLOOkJZVSainZPd0=,tag:yJhc+oPAukXODrwDo62kvA==,type:str]
    #ENC[AES256_GCM,data:nsjP3HSAa/XCBT9aV4Rop+WC+GEybcvFOpJkd2J3AZSSRHS7Qf8V8ENO0hm/AiMixTfWKMQnDyKJEFPeiQjlp1SbIMHKlAk=,iv:RMnjxvl1NFts9dpRHGFYBclj0pk5wEQy680z06EVxfI=,tag:si8ac1M9Lg0fCsNEl2qzmw==,type:comment]
    #ENC[AES256_GCM,data:26leTUulU/WI6NRQRFk56lQLkwe7PLgUmnFk4XRnYaH8gd8/h2YL06aJo8kW3UKMwILAS83Q,iv:9DoQ6jhPCD/0+rCAOChPNrfCT869Tkcdw2Sg57xM+ZQ=,tag:WIQ4N2PZXdGui4RsYqn/9A==,type:comment]
    #ENC[AES256_GCM,data:fQX/M+qI+t9RtP1uV9QsDIe/V5x/a4oOpOIM3NaqheyzAx4=,iv:YgM2lR4i5UI1QClka2lxs+USIyAk+sbLPq4DFJjm24Y=,tag:/nxgmHo6wkoeaCiv6LIs+A==,type:comment]
    #ENC[AES256_GCM,data:sVTu8fn5atkX8/WdMZ+BVrsDYvjnvE4DWqvKC6KyBYwSuDoehrGv,iv:PXsoNbhMWRC+pqadzJ0GiDAJw8MEywRV2rLraNmJyE0=,tag:pwiynXHr3nPOc9JDubSjNA==,type:comment]
    #ENC[AES256_GCM,data:G5cvUiV5eVZfL7QsKIw=,iv:3Ce9wNnEjquxRmS6NduJ89M0KfEbrGe1kJ7hrmB9JAY=,tag:pvVphQYS22TDSVn1pUWWMA==,type:comment]
    PODNET: ENC[AES256_GCM,data:M5MvcqNs+N5z1oayLA==,iv:aw8WL8OLev+rmXqN0x3vgU4hv+OVuLr2ALmRzONnniQ=,tag:0IOoODAPesOoYMIhDF/J9w==,type:str]
    SVCNET: ENC[AES256_GCM,data:ih3g5u/q51LvC8+Rdw==,iv:4cpVNJ0fnK9v7aA/amd4+er/O1t1p0iImr5SYSJTvrk=,tag:7QbB6LpeC27uvix8Nnwzpg==,type:str]
    S3_URL_MINIO: ""
    S3_BUCKET: ""
    S3_ACCESS_KEY: ""
    S3_SECRET_KEY: ""
    S3_ENCRYPTION_KEY: ""
    DN: ENC[AES256_GCM,data:41yjeEXuGw==,iv:Um/3V5inXwjglVeLMlzc1DQBHNrYZIVo0j28hWJSNfU=,tag:uiSytKk8Mc7H3x+3RKKwJA==,type:str]
    DC: ENC[AES256_GCM,data:/XLK,iv:hB3FrHXjYOZrTha9AZCpDG3GRxv18/4CYfBAIsqewo0=,tag:VlJleHoSFNurEgKxk0KQ5A==,type:str]
    LLDAP_PASSWORD: ENC[AES256_GCM,data:ksRKmD1UHG4wHM0tnvoH5Amw/CPXNk4ZfYQYopbR,iv:FxevFw11sGl40P4Se42eT+LWPes8ml5mrrWr5h0efss=,tag:H3Lu1iYjQG8byZbg4ow3Ug==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZsXk1nMezLKutEl5McDfq4vipQ==,iv:SXHFLlW/WtmZJ940BPTAJpEQ73Y0c49L0R4NW9gl8Cc=,tag:OeZxwVgOZuGejGWvUrk0eg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:f/WB4qtCnrWpJ5fmBHI=,iv:MesvM1o1XV1Xb0MXCO4RetJQNZJritfh3p50HT0V0hg=,tag:4xF7b4kgavsc3x/nPUINRQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:briqipo1HBx+7CGyMjWs7mqSKg==,iv:euWJpxdm4w5W0Bf27frwVBlkSBHPWOa2/uFh3CYGs8s=,tag:8BP8w69KF5oh+kx4Q+s5Eg==,type:str]
    NFS_HOST: ENC[AES256_GCM,data:Hl1mgIzSygHBA/fd,iv:0XKTKnww9acavbegKDn6VCx4dJOloKDtKV+jmd0Pbhs=,tag:LXKPwnqcJ88Cl9sN4oSyNw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:HPHBTTbba1Z7XWYYoudEltRcegqBY3GbyhhH/82/389Bpp9AuA==,iv:mDtbLaN9Ps/nOJf9ERAKRXmtiU1ezjv6vLen1gQJUrA=,tag:ya/XnbyqSElELnQqazAoYw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:P4g/9+jMtQAo,iv:uEHwJ1g60+y1panK/DyK94xb/IPci94Oov0dmjcyJNY=,tag:+6+W4ZQwwYRcmGWRkZinbQ==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:pxFM6oQum2aXookojotALg==,iv:+0u9P8961Q28BlzDx5TgWR/z7lvVxaGMsgdCbb1W+nE=,tag:Uctkc4ur4eiwNfhQsrHL8g==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:2pa55T/PgxOUf0Y003o9pAa2pDe0dtfGBhH3eAjgu8Q=,iv:u4z1y1CRDa0KhPURIrxn/uVrHWHzQ07HsgoWH64Znho=,tag:4I1fPilWYWFVUFq4n22WIA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:x7Nv4suL,iv:y2z7up9ZEQ+jFTBQMrVA2T5QN7nCFqkFIVI3EUQxS1k=,tag:Xi8CMBi6teFG8tjpuydOtg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:NoAaTA==,iv:4gx+KzzyQoxuG7wlGI8gX3aLw/KcrhQYG7IgYY/A4Oc=,tag:4GaousWpmJiCTgkCmlVfSg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUForZ0VXWHdkTy92WmVv
            djlpMHM3cjgwa2ZUNFEzeXVqQ0x4RGRIUmxzClZ5N1MzRkIvME9zUmt1U1JFQXZ2
            UDdqVFFqSW8yN240L2NIVlN1TXhlUkUKLS0tIEZoQWx1Q1RvMTlKTVVpS2pOV0la
            VUl6cDJsaEdmRktIbyswYnZ2MVA3L1kKup/q2CjukXMmee/w4+jFq2+sNfSIt35Z
            aD+Tfp2h26/nTqjlh/JKtNRzBxcEW76TfzH3B69I/x6ceE8ftdYvyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T20:22:08Z"
    mac: ENC[AES256_GCM,data:+phnPEGiQYZVAKlXcg1l93CkLzbuiL55IxrQiQc7lLxvH4psvIaQEbKXUhm7nfXn3c/WkA9F3t9PuemVAWYqfqwAEwChxWhoUtiH5pwzxqigbd7VfSXttq6HNbAtsbwD5xVwnxKfOlyiiLx/hN9JejPjpneUloa8/l7zTSez++E=,iv:gsbTqYIVPmc8qzz3WLeRc2DmQiJr1uvaJavi4UsyzEw=,tag:YCFz+1MY0phk43GO9v0G1A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
