apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:rbLGvs0scfX8uZq6w77N8IfP6Qe6J0zjATvehYAqVswwQqH0UGTjrVbjyUnzUqHWKhslkM9Fkjt4SJjE0//QYR4=,iv:EyPaD6igF1apOBoXW6uyl8rqvEHZ3cFJry9KSkSKcrk=,tag:lfN0s/6jXAdhzBeqnD6qow==,type:comment]
    #ENC[AES256_GCM,data:j1+a48yTqVipz4yZ+BKYraXL4pmOky+EjXV5D/2uUq9XN/yiJ6SdlQ+yJ8s=,iv:eyLqBzV/+4553l52eAue3BypfKKreNbph1BaAOn7dXc=,tag:HeP3zUuu8bfskUXkyweImw==,type:comment]
    VIP: ENC[AES256_GCM,data:7eSN85XWpc1HRF81WQ==,iv:Etg2CucHIB3xeQm/FGKpiwdX73RyQIIvmRr4waFdTuM=,tag:KxncLarHEyJHx/RQ4xI8/g==,type:str]
    #ENC[AES256_GCM,data:+tCPU9fv7vXNJiwVlHFRt0atdrhtIBbKjztp,iv:marGImr3SKM0iGl49rtLaWQSHl8ejTRO8+JahSmXiQI=,tag:Lz7APi4pd2nYS5aXwWpUHw==,type:comment]
    #ENC[AES256_GCM,data:EEqobXWmvcsEnOvGlnHk7GhLa5Ayn0T/V8qh6L9zDSBeOXsPkTi+gey4ytwOU/ct6CIyfW2kPNf45lleurTVnagT+DH4eakTeALLFwePEgaWrQYZMkbo/A8=,iv:d1lU5XksZ67MTB3Nw4CsSN4Iwmm6ciFz1lJUXtnYmlM=,tag:Y/UyrCcEFTwGbRvmfsOdVw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:rLkOOUdD0ct12ZVGxg==,iv:UzlHsjqU8c4F/ylmiSXISC80XYgp5biwSfPVg0vDlZY=,tag:3mgsc51uwkfjw0saWlrYaA==,type:str]
    #ENC[AES256_GCM,data:iu2QfWjVWPP5noNlopOkO+GKAWh9V0XG+nAP9WiwgHrSwg==,iv:85pEYdp+Jdf5QQvvTMhqcahyQTbmg5aWJW0xUr7oIxs=,tag:yEHqmYd3WH2NI1mJj3ne4g==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:U54Co7+T5Ip5XYY=,iv:M2qSR3p6Volo64UIzvD8lxkx7/iydIgVKHU+gELoqCw=,tag:maSv7DggTAuwtfndBL5TpA==,type:str]
    #ENC[AES256_GCM,data:EGSE4xH8oDaf8okrcHbM5uo2Xq+zNY/ExmyKPMrfBznJ+GxsbipXKDFVLGQkgFA=,iv:FbRbCNItDT2YgcULyXL9KyKnqT6ZNSVO4oUEHvV/PQ4=,tag:ThGDZ1a6oq2jxCTd4B8rMA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:1/37wmVk7BAkonpF+nJz2qKybY6z1cEs6RUe,iv:q47/xpTvd5MzMNDSm23+JH72KOcv+fwuLaMqr1wM6yQ=,tag:tIdhcRzi5g6vENR8js5xKg==,type:str]
    #ENC[AES256_GCM,data:3oGwS1VrMx3b6etDiwW31XNa23TTYf9pdvFVBBTd4LuQ8MP7rswmaT/11tS6EZIGUJfOuXzfbDWkcIsvbzfMZoYCnHrrruRHJTW2FvgbjUhvIg==,iv:Jq/quraPbap0sWg+UA1XWwI0vh58eAPOxIxU/uutKe4=,tag:aP3EGAC7KgZo5KrbUElF2g==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:dGSKmXcl3hx4CKSsXQ==,iv:CEJAoTdUzf3cf3TgoshCRI9ibSzWDJ+WffKt8VAhwks=,tag:UdkpMmrAnt0LM1L+9hFJwg==,type:str]
    #ENC[AES256_GCM,data:mVNbZo08TG4Z6a4RWNwi4JXKU71hB1kTR5LJKc6s0ctp,iv:2bVNZLmQ279WSi3xHKoI8db+ABPrdVu5cxuS4ERQC8E=,tag:7xVgDHDwm2U/rhCqY3CUzQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:tI0HVpE24xHNPoKLjg==,iv:5YYg8keFZI2g9mdDJ3KZPquSyi6XpG31Sh+Ru0l2wg8=,tag:n6KH4QnhWNpnYEz7QcGxRw==,type:str]
    #ENC[AES256_GCM,data:Ls6ZyLLPhKqb1rXloz8WpoEAB97UN1i4iWX+rV7auEpvBhQmEfQA+Ho0unIbgBI+44dFa29M4981WIBT/r8gI5Q8pbkNYjKFGL0XgyRh010=,iv:ifoy1fOqUlO5QsJvCEr/ojuJWXZwM6+yBRcUf7CpjKc=,tag:BlzSGq8dhOfVQp3TcgNdMg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:KdcNd51tmGZxjK6dEQ==,iv:8uK4C4NxXrC6l5Sk4d5h8JZsA4vkjkD0tZTAoTiY3u8=,tag:vcxA9DQte+GZtTBd97GWKQ==,type:str]
    #ENC[AES256_GCM,data:7UQnrCe5gJxfdewMwXj4BuRhkfE3S0MxnfNhYBIjAqKiW1oeVy5A8YVTnm3u6XlxjWLRa0K5YZrTjfobCutOmbeAPSCN+/ZKitO04gHJ99bbyv1h5soY,iv:xMZpzPB0jVT0c7PX9u3Xrbof2JXdVa2baaijd3K0gnY=,tag:aoFGiaSDM/xEqiW9VQUT6w==,type:comment]
    #ENC[AES256_GCM,data:NKpSfY5fcb2nulJb+t0GhILlVYPr91sKWi7HiS8da6KquRMnzGL2mHOjiJuhtMFk3iXXq8jM0zr9VJvWOY/kBfxg8X139pc3FK9pBCifsyF1oK614Gu8qFCMs4pN0xsJ+dz1mUFzxMPHHVh9sQT5ztMZC34FXt5vpS4LnA==,iv:WbP8EdsRIrb7CurbDlAGCoIav/o4JjvEPr/5ZMd7LPs=,tag:1cgpP/XvghTAJTnQK99N8g==,type:comment]
    #ENC[AES256_GCM,data:iFmozI8L9djU6gip5/tBDmF2QLTVuTh8QkK0i5HAzAOXXcugP8NAgG/iQASe5Xch8/9kzgsSR50St5GZXUlyM71ywmG0UQoJ+4k+sI/Nn7g=,iv:+T45PpJWjJbPtDvQxFjT0SgPdtlBqt95SDmqjJ+Cw1Q=,tag:AbfmxrVFsujfcoI/xAjfmg==,type:comment]
    #ENC[AES256_GCM,data:9g/1k1Gidm7WppsLpoOUi5eCTbgcJxkBcWy1u62xWnovGhda0WYLI5PF/lLjPKkcFTDXMpeJ,iv:yEH9qqBYjL4cFV8NeRgllYAo7TPtXcKRNXzKCy+Xi9M=,tag:2ZQDUHktcM+kPpMMJSwttg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:E25BnqYVwrGM3Ck=,iv:+Lovmjze7V0FU0EiDrdikKrEIqBEmm7P8deJxUE9/Mg=,tag:1/db2QaR2KIa5Vb6TmWZkQ==,type:str]
    ZONE_0: ENC[AES256_GCM,data:2ZyxKdjO8j5G35bP0qlRauCAG9ktul9RqcmM/y7At74=,iv:Dv1e/l9eXwYBF7NJpagghcTi95wjcUuEohcErNyvzV8=,tag:zvkhJnb28MprRoE0/+D8DA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:s/buJgBRoTnPpy0KAvjgaaIp3LXS/A==,iv:EZQkzLkIi6/rUeq4LH34+qKTe3voSXdq+r9uhQzAzwY=,tag:e2pT02CTJaR64nqA3NLrgQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Oh6K/AKb5GCt4JgZCfPwhXNANpbnf36TpedC4PNqMSHOB7EKEcX7Hw==,iv:/Tu95LaWspefAf6P+fbE/kzFiOk6PdTGPTfXzjznZnQ=,tag:BKaGEbcwbLTpY6+/03FXRg==,type:str]
    #ENC[AES256_GCM,data:G5RshRttaoxxoaoHoqwGGT++sfUKnCl2LybXZWWk0qGNQDy6GFRNWtKoT/KXr7IYQLQpOpXEQW0=,iv:li8ZexN3eb3b3ElFebuAkhbS7M6ySpMkz1mZQs4r90I=,tag:wdgPjT4gwYQRAgG7fPpvsg==,type:comment]
    #ENC[AES256_GCM,data:aoTXx5yW3lMyH8h0mmsH1JKYpmJvpNXgRw==,iv:bRwUeGBtanWg80d6R338rOYc565vbsJzQ1cDuiC0Kk0=,tag:ROO8U6+6HDyRpllciOsRKQ==,type:comment]
    #ENC[AES256_GCM,data:C7d2nu0nGyWBrO+zt7ESaiILSLaKEJVZAT9qhi87ryMeePOin2fTGlwwh83qNDtwK3N4q2dC/VSG1TW6vow6fYPDxYlyRFICbS6uNOw=,iv:CkLM4CJfQ8VobWTgzlxCh1Mq3WAwNXQopnn186kbXUQ=,tag:X31nN7gBiXxtayKMbpFpcQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:VhamQRJ8QKETIJlDuO3VVqEJccJZQ6QAalDs5vmJaOuA8BW4Byas9Q==,iv:PdQV2Cs6zuHiaafKygrB4cLZ390HSI4T8O4XeYD4JgE=,tag:EezFu/gDm3u3ztZkvr8tRw==,type:str]
    #ENC[AES256_GCM,data:5am7aG3sEv6PwQN44WwMCFhXaciV4Yj71vXQBZRM0/+BpcexkeAh1ehfCSnS+M+VkWP+Q38CS/q2PjCzN5ugAhjOrRErH8c=,iv:ilSiZFw35YnJPjRRI7UTsj1Ntfs6QR4u9U8wpukxat4=,tag:KHKsz8VvD98CGDNAmHdBig==,type:comment]
    #ENC[AES256_GCM,data:s0Yz4iOqFS63BEWKownOxNhnU8kWBAnCPHapJXhF09j+Dqy/Q/emDS42qagO5rVcwZujT+KV,iv:TOYaJFxpdhdin/qD0EF0eWkztImRyS/Kq1M8mic2gv0=,tag:JPapb/4XiB/AG0a28o3E/Q==,type:comment]
    #ENC[AES256_GCM,data:Nvdn/fA3YPK2upAhzCKlWxvTfFFNqiw0oGBb7eGDDrpWp8s=,iv:xSxgVBej986aVg47vID454X+Xxg04oPRgghNMOOYlUU=,tag:NjqPEzgnVSFnGJWlfYR5Vw==,type:comment]
    #ENC[AES256_GCM,data:+1BloRrRhw1aF4dkVgSPF79kcOFN2dd1uziyOcdMmXV8cNoB574j,iv:zbkFk2mp34wdAN6KE9jAClTWj5+xIxuzlDnOC8CC5XE=,tag:0WrlSJCLoypI9UL76WO9Aw==,type:comment]
    #ENC[AES256_GCM,data:aDmBfKC45b7i3Mv3oek=,iv:ix3XcRAyAeJB3JBJIme5MatlQX4aWLSAChD/PtP+wKI=,tag:BiNFbfiLAjjXtn/9zNWPxQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:7NqqAW3SJw7ATz4EOw==,iv:wmRmHM2wgO+IoYNViuOEqGJfX6TY8yoF/gxbR5xzTys=,tag:+JZnok186ztZsJ1jBSwHhw==,type:str]
    SVCNET: ENC[AES256_GCM,data:EaQ0OWd146wfElniGA==,iv:uoKtTqeZ0ijJ9ZxpXR0bRBXIIl7jpDhT02vLdSYB6cM=,tag:FrP83NHfUDv79DYwOERkOQ==,type:str]
    S3_URL_MINIO: ""
    S3_BUCKET: ""
    S3_ACCESS_KEY: ""
    S3_SECRET_KEY: ""
    S3_ENCRYPTION_KEY: ""
    DN: ENC[AES256_GCM,data:5Hck2X9TvQ==,iv:jTdD/0ux+En3jYXw/huDsdEg6hWqhahdeu9jDRQbZEc=,tag:CNZEJmTQRId3kzd5iZG+dw==,type:str]
    DC: ENC[AES256_GCM,data:/Gf6,iv:9NC26ebXeca8OXRZrLDzU13uO4WloLi3X6fmrYHpb/E=,tag:kvAVLfvBHglVb0E3D2apHw==,type:str]
    LLDAP_PASSWORD: ENC[AES256_GCM,data:XDtpOuvk46JLaE/pfDMzigu3avr7NVYPZL+RKQM+,iv:sytxcoeR0tcXHc3JCHCkinF63qF5ViMkDXccgz8VS+I=,tag:agb5O1F+AqIqrzt/zsEGlA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:eXUa00fZF3ThSOX8W8NjatA5jQ==,iv:+gQLzL9hXapboFlMKSJPxw14RS8SCI9iDSj/JXBnnhE=,tag:HFF3XNjsZbHVn0z6EahCxQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:Pk72k9NFrbnEv/0GGPQ=,iv:YoatG9xF2GUHEKgEQviYFAKxek4OAH+AoaQIJlS7mgA=,tag:PvJaPSznkz09roEMButfJA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:JW1TAHk2170VyggtzVjGuWNoTQ==,iv:ZhKo1FgOhYg0w9A4LJRsJxo96aw/JEoMP2el6mkscbY=,tag:UJM2/hiUBgKkd4Vhe5AI/A==,type:str]
    NFS_HOST: ENC[AES256_GCM,data:up9wiFgKaRea1IoI,iv:kPv2Av/ewX0hO86L92I5YdWfnAUycgNAQqTuXR86X6A=,tag:F+ovn0wLTQH5Jwgx2W9ASw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:AJwclGVqyIMWm2KrvyFhhdOrM3X392mvBRVhxWgYyBM0i+jEVQ==,iv:WQLfKnn92g7J8IPGoxRpaOA/mtwGWxoin05h80bJBDA=,tag:D5wOtiser/D2cuSAn7o9ew==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:/I5alCd8aqU0,iv:x0B4zlDfF4myeZvGSsEvjugt6kQi3PenSKaziaSLrxg=,tag:luYAXY8mOpUhS/VgXYBxEA==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:hE9IXdbBNyP33SvRZi09iA==,iv:OactnpjtkVKXn/7syYfHB4XMD7DuNSYJfsIBE1/486U=,tag:un3lYNd+cpxWhdHSzOASCg==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:SXSlEOKUqvfWL9ASgKcF6aIuHMBZc8Y52oTP8YwZRTE=,iv:AX4r86zsm1RjqfV61EFMd4nhQJvXBvqJb8ZNyfygArI=,tag:7dC+sRasoltq1h5dRt268A==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:jQkLeofe,iv:Kbvt1mO8lXMat11MWc166Q1Me34jkgqfhlgzyJtrdnU=,tag:ewNtdo02IdfZduD2HgoX3w==,type:str]
    SERVER_CITIES: null
    CLUSTERNAME: ENC[AES256_GCM,data:D6X27w==,iv:y80YWKLheJIwIbggtJNxaJLoRxzFljr053VKp56VpX0=,tag:lNHQIgamNqzKLpIuMBBSjw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYREJjVjF0Z0VhMHhOSC84
            OFNQTERRcHVSQXkvazY4ZWFhUU9pempOZkVVCmJXRWFqcWNMRFk1cUJnUWJMOHlt
            TkdEaUVGbENrZnFtem9kTWVaQ0Nna0kKLS0tIGZTUkd2OG9jTWpONjZXM2NnbHV5
            YmptUW9JdkcwTkJDYVZkOXkwcWRxcWcKKPWmrOPVeix3cZ+B5/y4m7jh/c9cERdD
            tK9CffdDwRfEiwCNsbCDnPx4eHYclqYqSK8dUnFFlKjYyHZW6XQ4fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T12:16:15Z"
    mac: ENC[AES256_GCM,data:LsKpklOemJRVWlywp7FPRQ/PBkpNf8DTxzPR5UQIzHw296uVGE+GMAo83f5u5LpgG7pLC5vY3HJ3wQAVVVsLRUO++8dflk49ngo78O9CLLEo2zA2kywefbTOWM1igrmNGwgyli/SRMvvycQHukwbfI4g5c8vWOCCmkiUT9feYmY=,iv:pdhP7x3XSpzyYUVPpXLPTVioqagBI2i9aQi1Z+GC4RI=,tag:grSizKP8a/rdTCbP0LCfLA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
