apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  #ENC[AES256_GCM,data:fDWb26WGtJKGr9Dt30AIKjl36sDj3Dt2UwamvCaXvM5/0gXFloGYlyiuj1Ex7E8gPCvE8hvhndfVrzyZ5JqShNc=,iv:pCTvA9tQ+fTzfMEnG1dVmQ2oDYRxiWm+IzWBE+k2EeM=,tag:LZJQa7oSqsKMB93dgGtB5w==,type:comment]
  #ENC[AES256_GCM,data:ItkZmhXRIu0b6U8GFDASzGxg3vD/wp9AgBCm47Fr8s1SWU2B3KtH3DJxlqM=,iv:+ZzI5tMN2DPmhK9s3F8tbhviTRLu/o8DXahu/Q0KFdg=,tag:HYBMRgeTfwbAwiVZGVF8BA==,type:comment]
  VIP: ENC[AES256_GCM,data:Co+t+8vKSSYhknX4Fg==,iv:PlM7SWKQzZBR5ur5jmlmQBP3h/SkKRuLBgGb7WhZ6kw=,tag:sYV1UHI7JaJxVvdf5CaTcg==,type:str]
  #ENC[AES256_GCM,data:nxaz6JIpQlw+RdGE358LcbfgRngNgFiSndx2,iv:MKZwp8iLQHUdUsDRYpfiwAWlQRp8L3N+qQU1c82YTcw=,tag:codurvDZunYUPIDj1NkL7Q==,type:comment]
  #ENC[AES256_GCM,data:ngB2sbkSbjVHrNA9/U2VJcVn6HSbKX52tF2NXrAAM9HQubZqbKE5EHKLDkMtC0BGNjqOs7qQR7ci19cQPgbsSopIT0zmXPf1mIWwhP66jEoceQCFboejNAM=,iv:6ZCt6YlXFC0w3F09wQicDyL7P0f8wmmlFH7iuq809Pw=,tag:+14MTABsPeF1qiqjojQBZA==,type:comment]
  MASTER1IP: ENC[AES256_GCM,data:Tih4bFL0FXwBIKT6eg==,iv:1QBtF/L13ExPr1nnOQnoD+N1J40HnMCsEaG2LXdTE20=,tag:bSde9RI04OUxoFTWp1vbMA==,type:str]
  #ENC[AES256_GCM,data:+aphnOIakQeiu/c70xWfk3ARTnWcyEhXN9Oj3Hnk1tP3Ww==,iv:MNGKVIXZQIFSwjSN8E6aDscmM3fx/t8RVk++mMvGs2c=,tag:zoLPCTys0JCML1yiVyVWcQ==,type:comment]
  GATEWAY: ENC[AES256_GCM,data:jQTn+IQ35QYryIs=,iv:ktuCfa0nvrRSJwRIGDNRyR/bbsLeJugesa+M4zlCCg4=,tag:nkkOFZDMUM83QHm3VYY5ew==,type:str]
  #ENC[AES256_GCM,data:unvSryFZ0t/AtK+JtpxmqDu4Dcvkr+8N8F+SpyDh6UXnFLtWtl/xWuGe2vA9ByY=,iv:Pq3rTyWjo3Zm/zQCniFFsI54KhhtZRJ9TYcRSEN0W0g=,tag:a84IqgL8HQJrj6sSCJEU5g==,type:comment]
  METALLB_RANGE: ENC[AES256_GCM,data:aeHN83s7y12CkCIw+VrW8V7cRuqvHWRtYMQx,iv:1RqiJsK6I61eQy8RGpQ0BPkETd4SCAwLZ+K5mDn45O4=,tag:4nf2TC/hoEoObmUFnrwZAg==,type:str]
  #ENC[AES256_GCM,data:6naswUg2oB/M/PC/yfvsCiVdSde0I4f4EhLYD3lhu9Zi/Jmk7gSLocjDuOZx4BjzJQUO1rVUvYB7Ug6jYFO6jCkGkovSEOzM8kZAZ1rVBBmIdA==,iv:J9m2VYVr8TN6jHw1G2OVsW5F/+EwJhLLasFu3NNHtcE=,tag:o5xYqfIgOEHRDApFpXL2wQ==,type:comment]
  TRAEFIK_IP: ENC[AES256_GCM,data:ltJpuoNd4B3ZUMJ6/w==,iv:61TRsg4nCUj0YNrgJZKl83KIdS4V0DEnPDkSNQLcWpE=,tag:Xmu8x3TUKiTerSs4YRIj7Q==,type:str]
  #ENC[AES256_GCM,data:ddRQJbRvp72XsfSXfu6q0C2NOB4iTyFRtsJ+QjY4Ig29,iv:BMmfrpFfu6quiEOxAy7XRgmVLI1+nuXDD85E58xF5tU=,tag:D7pD4c2991Q/qlG/K/079A==,type:comment]
  BLOCKY_IP: ENC[AES256_GCM,data:4bNjDnICOTkmPL8+0Q==,iv:cvV/IGY8h3I9NI4Cb5K0G6mlL156onXi4uKNkQ7mYr4=,tag:fAapluw4K/96mfYXazfyvA==,type:str]
  #ENC[AES256_GCM,data:HhoPkUoH3LHsweRcMxqT6NaMwZi2wecXgd7/34MwAji5w9uG2yQAtl93tDpofFpsYBhqYSZmS50UEXboiwKefTQ6eIE70TI3ltvEki+sePI=,iv:ZOYdTG4WJm368MzeMwUfIV5aoNNA7jJyOwhlZiRYUB4=,tag:nIA3UPct2vsnL8goP8XTVA==,type:comment]
  DASHBOARD_IP: ENC[AES256_GCM,data:UhHGX+iN2n/6hfgwaQ==,iv:A0GQS9YK5fEbziMHW1QeNEwB72yUh1BYRfYRzBNzcuI=,tag:3ONpdsBFZDUTXqiIVg9+2A==,type:str]
  #ENC[AES256_GCM,data:dgUpwS5j2EE5tk3E7ifF9lBfaOEm8degdiVvnZSRY+sItXneaFMJpOO2ztD7gnw55Q1f7LiRi13YTnTEGm7BJwZfWLTOjbAQDi2B8wvJUtgMVmeHV6h7,iv:AYmRb2jka4demFsLC63UxjbejH4N8VHzKJGpRl9SvXU=,tag:p1bjRB85evaa6Y2kFyxozA==,type:comment]
  #ENC[AES256_GCM,data:4NAZPxDqJyPrzZx2sOVcNGvg1lq3OLMzJXl6cowrBZ6NsOKFE7Z97EaWL4zyKNvYXAMd916b+LrDxhio7JCJuerxW1sDE4q5AtBHhGORhbToGT7X12kypsSYBsw6aJarh8Mofz29hGJfaGPs/OOMW/3a+F9XPYxavzyXMw==,iv:UsvpT+tQF8f2jbr8hTvHZNW2pFcAbsZnvn74ZNiVR+E=,tag:CqGJ6Hin56USXvZXgJkUGA==,type:comment]
  #ENC[AES256_GCM,data:vHaH8Lksc8V3i5mFlI7Mw8DEt/ZvJARol2YZb6QnttQGnYHr8vtiVW83sLYx4Y9mLJ8eC4NohZb/uTfBC3N+zH2y58SjQ4WmuieBUPxpHGw=,iv:W8gLCiE78VwIj9vT01QzXc9Z2rxqV06NY2iYlQanseQ=,tag:psf1kQ5dQ56biLMQTvFgCw==,type:comment]
  #ENC[AES256_GCM,data:E4jdakdQEfo5WeVDrvJLex9EOMjzIHF9y8RYTAJfv0oUkceXEwpcQBbmV880yG3WDDNOZrgw,iv:PfVudRj/YYvcPUd7GmsN/gf6iCN6nF4Ct2ycx2fNRQA=,tag:dQ2flxAu3J47WyKii4Eghw==,type:comment]
  DOMAIN_0: ENC[AES256_GCM,data:YCc+VN6dxoSmXCs=,iv:0qvOAZFZHF5mO7R0EdVLFYKCVkYUTlW2BWRjqyJrink=,tag:IoFnFVwPu5JF8clWIlmN6g==,type:str]
  DOMAIN_0_EMAIL: ENC[AES256_GCM,data:i7ecTnZ+2m/gMX77xiU=,iv:hK6AcvsdRYqYQrIugd+4uvLuKfcBCORZC+4S/GA/pOg=,tag:NIf79M3HVx1TYbZpDr3XUg==,type:str]
  DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:5kvclf9IuAS1JLMmVrtSL+1AaFCzfWWUHw==,iv:AfDyydQtctFCrnqSc6vXXgZhu1nAn2nNPVMMT1uRoSE=,tag:yePnfVLRIDmnUGVThIf4Fg==,type:str]
  #ENC[AES256_GCM,data:GzxgRlszoFqljeuxuljDvlXt7eN2NH+U81ZDR2kJ7e5T+bxjVNS7mra/h1zWD6/6n1+ydh8t+Kk=,iv:3hsCzddsC0KntmYzHckczAUmK0ty4340L6OAMTEArms=,tag:c6vCGFtzYYzMb8zUbi4Bew==,type:comment]
  #ENC[AES256_GCM,data:IpjTorlxs/7XRZ6kCGZqZjRv5udX7qQCzw==,iv:zT2GLZSwZH5v+3/2JZjLKSMN9GMNOcwS1fjjr7VfsXo=,tag:IQIwrPlSbs9MbNd0TlW2nQ==,type:comment]
  #ENC[AES256_GCM,data:mH9vlpVci4OzlLgXi58ze9Xc51b/cU83twAomi/tyWYH5mGYug2iuhp4Y3AP7UAESxRiZqGAUS2Fs5IsgjJ3Oj4ESTf3BDNP8k2rc9Q=,iv:7McZbX1CAbkyt2pO6ZzxkT/XtR5fn50+2ixgRgAfU10=,tag:9MIYiLXF11QfmxLdd1Ksyg==,type:comment]
  GITHUB_REPOSITORY: ENC[AES256_GCM,data:b6KBA/B41ET903Ls04L19psEq++/QGzpEJ1g2mK2cHWSJmmGO7yycQ==,iv:eNjVT2DLG7V7vr6fLP4RzXb797ILdTLyNdc0dlcyKLc=,tag:A+O2yX2BGFd+idI+sPj8tw==,type:str]
  #ENC[AES256_GCM,data:Kt+hByVf/xhLZRMs7Y379F/9wgbcOyKAOHFcOidn7c3qZm217MkDd9HCdrf/qPk28JOxL0VfxSjZt5IEcKK9aJUGQ6Bscv4=,iv:DsIrueU403W/WVUdKlZKuRQUGHG/RnsL93Y6z9qHgPU=,tag:fOm0XmKWs5H+NOS42w0Jjg==,type:comment]
  #ENC[AES256_GCM,data:C3FnJW3PPTr9s3e/l7zFi/9wM2A5DwKtckIl3MK2DvDchsL11wgtMumMcBrf3+EpeltpLqa7,iv:IyzjoozwEM8j3y5lXq41iAQgKoUDm7gA3H+2eRm2Ms4=,tag:YUsnnw51iTYN5Z0oUaE51Q==,type:comment]
  #ENC[AES256_GCM,data:aS0tT5W719vbEPQybXpezGsYr32Ghwmm6CH++wrsUikDE0c=,iv:7k5Sc6SjX03XNQDrn5tLbjatGI7N+8nXt6jKz7ywiS8=,tag:SZYWyxu46bSNTVh6rS4jKQ==,type:comment]
  #ENC[AES256_GCM,data:42P0enrlbYpqBYXscWX1WfiEHxD4JXdI6/MSlSULq5nDED92k1Em,iv:bbxhQ7rnjUDKur9CW8McSgD0/aS06+fnvLnKwL9kQmw=,tag:xs6Tv6RoVkeAUO48ruvCrg==,type:comment]
  #ENC[AES256_GCM,data:mOFJ3vGi10JfbQj8VRA=,iv:u/bCpV0yW1mU3LE7xRn81FOV77y2H2iOC4u6P/FKYGI=,tag:nK8BvO5m+1h1tGeSaHCV9g==,type:comment]
  PODNET: ENC[AES256_GCM,data:vEl7aEnobI9/V5x33g==,iv:67ofxS8p5X9Tnp/sZbVtzzDP386R9xI4ODI8XRrx1JA=,tag:977REDj86LYhKuHo93fvjg==,type:str]
  SVCNET: ENC[AES256_GCM,data:mtxhEFDIitEKJi5YUA==,iv:sIzhf8x945KnwNcpqn/7vZUtgN8+Av3+q9YmuifMkTg=,tag:VSi6YVeHxpuC+OZQUee0uA==,type:str]
  CLUSTERNAME: ENC[AES256_GCM,data:y1/WwQ==,iv:RtmkUk3534hiGLAW+8xY+A2xKhEW/ruc9ymnzyKT+7g=,tag:kTNaXBjt2mmdFsMmdECcBQ==,type:str]
sops:
  shamir_threshold: 3
  kms: [ ]
  gcp_kms: [ ]
  azure_kv: [ ]
  hc_vault: [ ]
  age:
    - recipient: age1eua6khdgdqv4p8zhxhjzv94ylftmj6lr0jcz4eu2fjyghgpg5fdsldalh2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbEhRRUh6WmdMUEt2OVNL
        a2c2dFhQWFM0MzJKWitoQ2hvYm4wQURVU1hNCkQrOU5zOXJJTm9QRU04NVJGVHZG
        N0JzakJyM0xRWTd6V016eERESFZEWlkKLS0tIGtNRm0yYjJOUUxSUllWN1FNeDho
        bWUzVEFUS05EM3RTRW5hdk1sNUUvVm8KwNBdqIjbY/o+McZCNrU9Qm4WO5GNv0iB
        /A/XToEpPm69BiOQvGdj0AaMtuLjue4IVoBysgg3Hbtvokta6fm7VA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T08:36:11Z"
  mac: ENC[AES256_GCM,data:d/0LSLUQX/GE+Us0emBd6AagiYK6dIPODUafe5vwWjTLNQmbLVItaOQc+O09SthpsLij3LsyY4CkisjHszK6V2vCRSMjyjJVSj5fewC+rYcZo3c+4+zYhwUwZQgvS0spJPKiOuHauqOSeBh3QX7r/22ksXW2M9mBsLCY1+7j2eM=,iv:CA/gbHXForiNFkCW9W5ofcPysd1+VzlNpPdReHi+hpk=,tag:eVW1pHRqTgSPs3to4D9YRw==,type:str]
  pgp: [ ]
  encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.9.4
