apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: sonarr
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: sonarr
            version: 24.8.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              middlewares:
                - name: auth
                  namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: tvshows.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      persistence:
        config:
          enabled: true
          type: nfs
          path: /mnt/tank/apps/sonarr
          server: ${NFS_HOST}
        media:
          enabled: true
          type: nfs
          path: /mnt/tank/media
          mountPath: /media
          server: ${NFS_HOST}
