apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jupyter
    namespace: jupyter
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: jupyter
            version: 11.8.51
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: science.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
      persistence:
        data:
          type: nfs
          path: /mnt/tank/jupyter
          server: ${NFS_HOST}
