---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 27.0.14
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    globalArguments:
      - --global.checknewversion
    ingressClass:
      enabled: false
      fallbackApiVersion: ""
      isDefaultClass: false
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - --serverstransport.insecureskipverify=true
      - --providers.kubernetesingress.allowexternalnameservices=true
    logs:
      access:
        enabled: true
    defaultCertificate: "domain-0-wildcard"
    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        enabled: true
        externalTrafficPolicy: Cluster
        ports:
          web:
            enabled: true
            forwardedHeaders:
              enabled: false
              insecureMode: false
            port: 80
            protocol: http
            proxyProtocol:
              enabled: false
              insecureMode: false
            redirectTo: websecure
          websecure:
            enabled: true
            forwardedHeaders:
              enabled: false
              insecureMode: false
            port: 443
            protocol: https
            proxyProtocol:
              enabled: false
              insecureMode: false
            tls:
              enabled: true
        type: LoadBalancer

    middlewares:
      forwardAuth:
        - name: auth
          address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.abmania.org/
          authResponseHeaders:
            - Remote-User
            - Remote-Group
            - Remote-Name
            - Remote-Email
          trustForwardHeader: true
      ipWhiteList:
        - name: local
          sourceRange:
            - 10.0.0.0/8
            - 172.1.0.0/12
            - 192.168.0.0/16

      redirectRegex:
        - name: traefik-dash
          regex: https://traefik\.${DOMAIN_0}/?$
          replacement: https://traefik.${DOMAIN_0}/dashboard/#/
          permanent: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: traefik.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
              - name: traefik-dash
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        tls:
          - hosts:
              - traefik.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
