---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultCertificate: "domain-0-wildcard"
    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
    middlewares:
      forwardAuth:
       - address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.abmania.org/
         authRequestHeaders: []
         authResponseHeaders:
           - Remote-User
           - Remote-Groups
           - Remote-Name
           - Remote-Email
         authResponseHeadersRegex: ""
         name: auth
         tls:
           insecureSkipVerify: false
         trustForwardHeader: true
    ingressClass:
      # true is not unit-testable yet, pending https://github.com/rancher/helm-unittest/pull/12
      enabled: true
      isDefaultClass: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: traefik.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: ""
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: auth
