apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: whosaid
    namespace: whosaid
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://abmania.github.io/helm-charts
            chart: whosaid-rs
            version: 0.0.2
            sourceRef:
                kind: HelmRepository
                name: abmania
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
    values:
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  WHOSAID_DISCORD_TOKEN: ${WHOSAID_DISCORD_TOKEN}
