apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: veggie-planner
  namespace: veggie-planner
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=oci://ghcr.io/fait-maison/helm
      chart: veggie-planner
      version: 0.0.4
      sourceRef:
        kind: HelmRepository
        name: fait-maison
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: domain-0-le-prod
      hosts:
        - host: veggie-planner.${DOMAIN_0}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: veggie-planner-tls
          hosts:
            - veggie-planner.${DOMAIN_0}
